name: test_checkout_location
on: [workflow_dispatch]
jobs:
  test:
    run-on: ubuntu-latest
    steps:
      uses: action/checkout@v3
      run: |
        echo ${{ github.workspace }}
        echo $GITHUB_WORKSPACE
