name: Replace JSON Values and Run Script

on:
  push:
    branches: [main]

jobs:
  replace-json-values-and-run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Replace JSON Values
        run: |
          pwd
          ls -la
          chmod 755 ./*.json
          json_file_path = ${{ github.workspace }}
          replacements = "${{ secrets.JSON_REPLACEMENTS }}"

          # Parse the JSON file
          json_data=$(jq -r . "$json_file_path")

          # Iterate over replacements and update JSON data
          for replacement in $replacements; do
            key=$(echo "$replacement" | cut -d '=' -f 1)
            value=$(echo "$replacement" | cut -d '=' -f 2)
            json_data=$(echo "$json_data" | jq ".${key} = \"$value\"")
          done

          # Write updated JSON data back to file
          echo "$json_data" > "$json_file_path"
          echo ${{ github.workspace }}/tes.json