name: Replace JSON Values and Run Script

on:
  push:
    branches: [main]

jobs:
  replace-json-values-and-run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Replace JSON Values
        run: |
          jq '. | .city = "${{ env.JSON_VAR }}"' tes.json > replaced_json.json
      - name: Display replaced JSON
        run: |
          cat replaced_json.json
        