name: Replace JSON Values and Run Script

on:
  push:
    branches: [main]

jobs:
  replace-json-values-and-run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Replace JSON Values
        run: |
          bash ./repl.sh