name: Echo Workspace

on:
  push:
    branches: [main]

jobs:
  echo_workspace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Echo workspace directory
        run: echo "Workspace directory: ${{ github.workspace }}"